apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskboard.fullname" . }}-config
  labels: {{- include "taskboard.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  APP_VERSION: {{ .Values.backend.image.tag | quote }}
  CORS_ORIGINS: {{ printf "http://%s,https://%s" .Values.ingress.host .Values.ingress.host | quote }}
  POSTGRES_HOST: {{ include "taskboard.fullname" . }}-postgres
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
